#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@xupnpd[-1]
	add ucitrack xupnpd
	set ucitrack.@xupnpd[-1].init=xupnpd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache

chmod +x /etc/config/xupnpd
chmod +x /etc/init.d/xupnpd

exit 0
